apiVersion: v1
kind: Service
metadata:
  name: mysql   # will be used as a value in
  labels:                 # mysql_DB_HOST in mysql-deploy.yml
    app: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
  selector:
    app: mysql
    tier: mysql
---
apiVersion:  apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql/mysql-server
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql        # the one generated before in secret.yml
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv-volume  # which data will be stored
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-pv-volume    # PVC
        persistentVolumeClaim:
          claimName: mysql-pv-claim
